// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ewhauser/bazel-differ/internal (interfaces: BazelRule)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBazelRule is a mock of BazelRule interface.
type MockBazelRule struct {
	ctrl     *gomock.Controller
	recorder *MockBazelRuleMockRecorder
}

// MockBazelRuleMockRecorder is the mock recorder for MockBazelRule.
type MockBazelRuleMockRecorder struct {
	mock *MockBazelRule
}

// NewMockBazelRule creates a new mock instance.
func NewMockBazelRule(ctrl *gomock.Controller) *MockBazelRule {
	mock := &MockBazelRule{ctrl: ctrl}
	mock.recorder = &MockBazelRuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBazelRule) EXPECT() *MockBazelRuleMockRecorder {
	return m.recorder
}

// GetDigest mocks base method.
func (m *MockBazelRule) GetDigest() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDigest")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDigest indicates an expected call of GetDigest.
func (mr *MockBazelRuleMockRecorder) GetDigest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDigest", reflect.TypeOf((*MockBazelRule)(nil).GetDigest))
}

// GetName mocks base method.
func (m *MockBazelRule) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockBazelRuleMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockBazelRule)(nil).GetName))
}

// GetRuleInputList mocks base method.
func (m *MockBazelRule) GetRuleInputList() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRuleInputList")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetRuleInputList indicates an expected call of GetRuleInputList.
func (mr *MockBazelRuleMockRecorder) GetRuleInputList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRuleInputList", reflect.TypeOf((*MockBazelRule)(nil).GetRuleInputList))
}
